/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bruno.vertx.echo;

import org.junit.jupiter.api.Test;


class AppTest {
    @Test void appHasAGreeting() {
    }
}
