/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bruno.vertx.echo;

public class App {
    // Test different echo implementations
    public static void main(String[] args) {
        VertexEcho.setup();
    }
}
